### ISSUE TITLE
Truffle package zeppelin-solidity isn't  found

### ISSUE THREAD

**Issue by Eenae** [sc-forks/solidity-coverage#103]
Hello!

I'm trying to generate coverage for this project https://github.com/mixbytes/storiqa_ico/tree/036a57a6c71599b643145f4ec4e77d86b360dec1.

and encountering an error
```
$ ./node_modules/.bin/solidity-coverage
Generating coverage environment
Instrumenting  ./coverageEnv/contracts/crowdsale/FixedTimeBonuses.sol
Instrumenting  ./coverageEnv/contracts/crowdsale/FundsRegistry.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/ownership/multiowned.sol
Instrumenting  ./coverageEnv/contracts/ownership/MultiownedControlled.sol
Instrumenting  ./coverageEnv/contracts/ownership/SimpleMultiSigWallet.sol
Instrumenting  ./coverageEnv/contracts/STQCrowdsale.sol
Instrumenting  ./coverageEnv/contracts/STQToken.sol
Instrumenting  ./coverageEnv/contracts/test_helpers/crowdsale/FundsRegistryTestHelper.sol
Instrumenting  ./coverageEnv/contracts/test_helpers/STQCrowdsaleTestHelper.sol
Instrumenting  ./coverageEnv/contracts/test_helpers/token/MintableMultiownedTokenTestHelper.sol
Instrumenting  ./coverageEnv/contracts/token/CirculatingToken.sol
Instrumenting  ./coverageEnv/contracts/token/MintableMultiownedToken.sol
Launched testrpc on port 8555
Running: truffle test  
(this can take a few seconds)...
Using network 'development'.

Error: Could not find zeppelin-solidity/contracts/ReentrancyGuard.sol from any sources; imported from /home/e/storiqa_ico/coverageEnv/contracts/STQCrowdsale.sol
    at /home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:49111:23
    at /home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:60660:16
    at next (/home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:69109:18)
    at /home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:49099:7
    at /home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:96498:5
    at /home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:69014:16
    at replenish (/home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:60630:25)
    at iterateeCallback (/home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:60620:17)
    at /home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:60660:16
    at ReadFileContext.callback (/home/e/storiqa_ico/node_modules/truffle/build/cli.bundled.js:96494:14)
Cleaning up...
```

zeppelin-solidity is used in the project as a package as described [in truffle docs](https://truffle.readthedocs.io/en/beta/getting_started/packages/#using-a-package) and installed locally in /home/e/storiqa_ico/node_modules/zeppelin-solidity/. Truffle does't have any problems searching for zeppelin-solidity includes when invoked from the project root directory.

**Comment by Eenae** [comment]
Found workaround:
```bash
$ mkdir -p ./coverageEnv
$ ln -s ../node_modules/ ./coverageEnv
```

**Comment by Eenae** [comment]
I'm using solidity-coverage 0.2.2, truffle 3.4.9.

**Comment by cgewecke** [comment]
Hi @Eenae. If you are importing contracts from npm into your solidity files you'll need to explicitly request that node_modules is included in the coverage environment by creating a .solcover.js config file and setting the copyNodeModules option to true. See the README for more details. 

Thanks for opening this. Closing because it's addressed by the existing docs but please feel free to reopen if you continue to have issues with it.

**Comment by cgewecke** [comment]
I just saw your workaround - cool!
