### ISSUE TITLE
Error when running solidity-coverage on Windows

### ISSUE THREAD

**Issue by aleybovich** [sc-forks/solidity-coverage#194]
When i run `solidity-coverage` on my project on a Mac, it works fine. When I run it on the same project on Windows 10, I get the following error (in npm debug.log):

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\andrey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'coverage' ]
2 info using npm@5.6.0
3 info using node@v8.9.1
4 verbose run-script [ 'precoverage', 'coverage', 'postcoverage' ]
5 info lifecycle token-contract@1.0.0~precoverage: token-contract@1.0.0
6 info lifecycle token-contract@1.0.0~coverage: token-contract@1.0.0
7 verbose lifecycle token-contract@1.0.0~coverage: unsafe-perm in lifecycle true
8 verbose lifecycle token-contract@1.0.0~coverage: PATH: C:\Users\andrey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\dev\token-contract\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\andrey\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Program Files\Amazon\AWSCLI;C:\Program Files\Geth;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Users\andrey\AppData\Local\Microsoft\WindowsApps;C:\Users\andrey\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code Insiders\bin
9 verbose lifecycle token-contract@1.0.0~coverage: CWD: D:\dev\token-contract
10 silly lifecycle token-contract@1.0.0~coverage: Args: [ '/d /s /c', 'solidity-coverage ' ]
11 silly lifecycle token-contract@1.0.0~coverage: Returned: code: 1  signal: null
12 info lifecycle token-contract@1.0.0~coverage: Failed to exec coverage script
13 verbose stack Error: token-contract@1.0.0 coverage: `solidity-coverage `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\andrey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\andrey\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid token-contract@1.0.0
15 verbose cwd D:\dev\token-contract
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\andrey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "coverage"
18 verbose node v8.9.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error token-contract@1.0.0 coverage: `solidity-coverage `
22 error Exit status 1
23 error Failed at the token-contract@1.0.0 coverage script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any ideas?

**Comment by cgewecke** [comment]
This is stale I think...
