### ISSUE TITLE
Improve error indication

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#211]
I get this:

    Running: truffle test --network coverage
    (this can take a few seconds)...
    Using network 'coverage'.

    Error: VM Exception while processing transaction: out of gas
        at Object.InvalidResponse (C:\Users\...\truffle\build\webpack:\~\web3\lib\web3\errors.js:38:1)
        at C:\Users\...\truffle\build\webpack:\~\web3\lib\web3\requestmanager.js:86:1
        at C:\Users\...\truffle\build\webpack:\~\truffle-migrate\index.js:225:1
        at C:\Users\...\truffle\build\webpack:\~\truffle-provider\wrapper.js:134:1
        at XMLHttpRequest.request.onreadystatechange (C:\Users\...\truffle\build\webpack:\~\web3\lib\web3\httpprovider.js:128:1)
        at XMLHttpRequestEventTarget.dispatchEvent (C:\Users\...\truffle\build\webpack:\~\xhr2\lib\xhr2.js:64:1)
        at XMLHttpRequest._setReadyState (C:\Users\...\truffle\build\webpack:\~\xhr2\lib\xhr2.js:354:1)
        at XMLHttpRequest._onHttpResponseEnd (C:\Users\...\truffle\build\webpack:\~\xhr2\lib\xhr2.js:509:1)
        at IncomingMessage.<anonymous> (C:\Users\...\truffle\build\webpack:\~\xhr2\lib\xhr2.js:469:1)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1056:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)

Any chance to improve the error indication, so that I can get a better idea of where the problem stems from?

**Comment by cgewecke** [comment]
@barakman I'm not sure how we can do this. The coverage tool would need to watch the test output and interject commentary. 

If possible could you clarify what problem you are raising with this issue? Do you need advice about how to get around this exception? Or do you feel like the README is not clear enough about the need for custom gas values in `truffle.js` / when launching testrpc-sc?

**Comment by barakman** [comment]
@cgewecke:

Thank you.

Setting gas values in `truffle.js` doesn't solve this problem.
Neither does setting them when running `ganache` via command-line.

In fact, I am getting this problem even when I delete all testing scripts (JS) from the `test` folder.

I admit that the problem is possibly related to `truffle test` itself, which gives a similar error at some point, unless it is executed with one file at a time, AND with a "fresh" `ganache` instance on each test.

For example, I had to write this Windows batch script in order to get `truffle test` to work without breaking on some gas issue at some point:

    set FILE_NAMES[00]=Test1
    set FILE_NAMES[01]=Test2
    set FILE_NAMES[02]=Test3
    set FILE_NAMES[03]=Test4

    for /f "tokens=2 delims==" %%s in ('set FILE_NAMES[') do (
        start cmd /c "title %%s & ganache-cli --port=8545 --account=0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef,1000000000000000000000000000000000000000"
        call  cmd /c "truffle test test/%%s.js"
        taskkill /f /fi "WindowTitle eq %%s*" /t 1>nul
    )

So like I said, this is possibly a problem in `truffle` rather than in `solidity-coverage`, but I would nevertheless be happy to get something a little more informative than `out of gas`.

**Comment by cgewecke** [comment]
@barakman You're not alone in being irritated by this message, but it comes from the vm and has a number of possible causes. The easiest thing to do re: coverage is to get `truffle test` working conventionally first. 
What happens if you define a network in `truffle.js` as below:
```javascript
module.exports = {
  networks: {
   ganache: {
      host: "localhost",
      port: 8545,
      network_id: "*"
    },
  }
};
```
Then launch ganache-cli in a separate terminal:
```
ganache-cli --port=8545 --account=0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef,1000000000000000000000000000000000000000"
```
Then run `truffle test --network ganache`. 

If that succeeds, then all you have to do to get `solidity-coverage` to run is follow the instructions for adding custom options to the `testrpc-sc` launch in the README. Also, I highly recommend [this bash script](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/scripts/test.sh) (also check out their `truffle.js`) at Zeppelin as a reference if you're customizing your test launch by unlocking specific accounts. 

If it doesn't work, something is really unusual about your setup and I think you'll have to post a link to your code on github so that we can take a closer look.

**Comment by cgewecke** [comment]
cc: @barakman Is this closable? Did you get everything running?

**Comment by cgewecke** [comment]
Oh! Very sorry about that and thanks for noting it. Sometimes it's difficult to see the most obvious shortcomings of your documentation when you already know how something works. I will follow your suggestion add a note that emphasizes we run our own fork of the client.
