### ISSUE TITLE
Heap out of memory with large contract sets

### ISSUE THREAD

**Issue by barakman** [sc-forks/solidity-coverage#214]
I have a large set of tests.

At some point, I get the following error:

```
  1) Contract: ContractTest "before all" hook: prepare suite:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

<--- Last few GCs --->

[12036:0000021291071750] 13244000 ms: Mark-sweep 1421.8 (1566.3) -> 1421.8 (1566.3) MB, 196.5 / 0.0 ms  allocation failure scavenge might not succeed
[12036:0000021291071750] 13244199 ms: Mark-sweep 1421.8 (1566.3) -> 1421.8 (1566.3) MB, 199.1 / 0.0 ms  last resort GC in old space requested
[12036:0000021291071750] 13244392 ms: Mark-sweep 1421.8 (1566.3) -> 1421.8 (1566.3) MB, 192.4 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000014EEEA25EE1 <JSObject>
    0: builtin exit frame: endsWith(this=000003220CBF4A29 <Very long string[65884]>,000000D7217AD2F9 <String[1]\: \r>)

    1: ondata [readline.js:~140] [pc=000000D1EAB44BB9](this=0000015B6EB387B1 <ReadStream map = 0000020FFFE40949>,data=000003220CBF49B9 <Uint8Array map = 000003457A3417B9>)
    2: emit [events.js:~156] [pc=000000D1EAB4732A](this=0000015B6EB387B1 <ReadStream map = 0000020FFFE40...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
```

I realize that this could be a problem in either one of the following:

- solidity-coverage
- mocha
- node
- Javascript

Any suggestions would be highly appreciated.

**Comment by cgewecke** [comment]
@barakman Yes, this happens to `zeppelin-solidity` as well. There's a solution documented in our FAQ [here](https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-memory-locally-and-in-ci). 

For reference: zeppelin's [test launch script](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/scripts/test.sh) and [.solcover.js](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/.solcover.js)

**Comment by barakman** [comment]
@cgewecke:
Thanks.
I get the following error, which I believe is related to the fact that I'm running on Windows:

```
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Any chance you would know a solution to that?

**Comment by barakman** [comment]
@cgewecke:
Thank you.
The answer on your FAQ page is not compatible with Windows.
I had to replace `../node_modules/.bin/truffle` with `../node_modules/truffle/build/cli.bundled.js` (which is also OS agnostic I would hope).
It might be worth mentioning it under the [*Running out of memory* section](https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-out-of-memory-locally-and-in-ci) or under the [*Running on windows* section](https://github.com/sc-forks/solidity-coverage/blob/master/docs/faq.md#running-on-windows).

**Comment by cgewecke** [comment]
@barakman Yes try a higher size. The underlying issue is that truffle passes all of the contracts in a single batch to `solc`, then passes the output to `JSON.parse`. If that output is enormous the [parse statement](https://github.com/trufflesuite/truffle-compile/blob/develop/index.js#L108) consumes all the memory allocated to the Truffle process.  

It could be that there is a windows specific problem with increasing Node's memcap?

**Comment by cgewecke** [comment]
@barakman That's a lot of tests! Thanks for disclosing the magnitude. `truffle` is spawned as a child process of SC. Maybe prepending the command line invocation of `solidity-coverage` with the `max-old-space-size` would help? Once all the tests have run, SC reads (as a stream) from a file where instrumentation events have been deposited by testrpc-sc and then generates a mapping `istanbul` can consume, and passes it to `istanbul` running in memory. `istanbul` generates the report. 

Relevant code is [here](https://github.com/sc-forks/solidity-coverage/blob/master/lib/app.js#L294-L325)

Unfortunately those mem stack traces don't seem that informative about location. One thing you could do is get into the `node_modules` and log lines and find out exactly where it dies. Even if you get past solidity-coverage, istanbul might not be happy . . .

**Comment by barakman** [comment]
@cgewecke:
Tried `max-old-space-size` with up to 8192, no luck with that.

"a file where instrumentation events have been deposited by testrpc-sc" - do you mean `allFiredEvents`?

I'm trying to figure out my options here.
One is to change `istanbul` locally on my machine.

Would that be the code that you directed me to?

Because I did not get `There was a problem generating the coverage map / running Istanbul` as part of the error, so I just want to be sure I'm at the right place.

Thanks.

**Comment by cgewecke** [comment]
@barakman Yes, the events are stored in `.allFiredEvents` and the coverage data which Istanbul can consume is stored in `coverage.json`. If the process runs out of memory it might not fire errors normally - in this case you might have to insert `console.log` statements along the execution path and see how far you get.

**Comment by josh-richardson** [comment]
I'm aware that this is a fairly ancient issue, but I've just encountered it when running coverage on some fairly large contracts, in my case it was fixed by exporting `NODE_OPTIONS="--max-old-space-size=8192"`. I think this can probably be closed on this basis.

**Comment by cgewecke** [comment]
Thanks @josh-richardson. 

I am in favor of closing this as well. 

Have not seen any OOM issues (with this error) recently that can't be resolved by asking Node for more resources.

**Comment by heldersepu** [comment]
I tried the setting the `max-old-space-size=8192` but no luck

Here is the error I get:

```
> Compiling @openzeppelin/contracts/utils/introspection/ERC165.sol
> Compiling @openzeppelin/contracts/utils/introspection/IERC165.sol
> Compiling @openzeppelin/contracts/utils/math/SafeMath.sol
> solidity-coverage cleaning up, shutting down ganache server
RuntimeError: memory access out of bounds
    at Ab (wasm://wasm/0492dc6a:0:215851)
    at null.<anonymous> (wasm://wasm/0492dc6a:0:158157)
    at invoke_ii (/home/heldersepu/.config/truffle-nodejs/compilers/node_modules/soljson-v0.8.4+commit.c7e474f2.js:1:25622890)
    at vb (wasm://wasm/0492dc6a:0:17860641)
    at ccall (/home/heldersepu/.config/truffle-nodejs/compilers/node_modules/soljson-v0.8.4+commit.c7e474f2.js:1:8033)
    at /home/heldersepu/.config/truffle-nodejs/compilers/node_modules/soljson-v0.8.4+commit.c7e474f2.js:1:8383
    at runWithCallbacks (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/node_modules/solc/wrapper.js:151:1)
    at compileStandard (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/node_modules/solc/wrapper.js:207:1)
    at Object.compileStandardWrapper [as compile] (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/node_modules/solc/wrapper.js:214:1)
    at invokeCompiler (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:229:1)
    at run (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/run.js:43:40)
    at Object.sourcesWithDependencies (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:164:1)
    at all (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/compile-solidity/index.js:95:1)
    at /home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:102:31
    at async Promise.all (index 0)
    at Object.compile (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/truffle/build/webpack:/packages/workflow-compile/legacy/index.js:50:1)
    at plugin (/home/heldersepu/Documents/GitHub/ido-contracts/node_modules/solidity-coverage/plugins/truffle.plugin.js:97:5)
Truffle v5.3.10 (core: 5.3.10)
Node v14.18.1
```

**Comment by cgewecke** [comment]
I think this was a ganache thing...closing for now.
