### ISSUE TITLE
Coverage fails to compile on second pass

### ISSUE THREAD

**Issue by thegostep** [sc-forks/solidity-coverage#265]
I am working on a large project and not able to successfully run the coverage. The error seems to occur on compilation of the openzeppelin library in preparation for the tests. All the truffle tests should pass.

```
Writing artifacts to ./build/contracts

Running: truffle test --network coverage
(this can take a few seconds)...
Using network 'coverage'.

Compiling ./test/helpers/contracts/PolyToken.sol...
Compiling openzeppelin-solidity/contracts/math/SafeMath.sol...
Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/BasicToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20Basic.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/MintableToken.sol...
Compiling openzeppelin-solidity/contracts/token/ERC20/StandardToken.sol...

Compilation warnings encountered:


openzeppelin-solidity/contracts/math/SafeMath.sol:13:3: Warning: Function state mutability can be restricted to pure
  function mul(uint256 a, uint256 b) internal  returns (uint256 c) {
  ^ (Relevant source part starts here and spans across multiple lines).
,openzeppelin-solidity/contracts/math/SafeMath.sol:29:3: Warning: Function state mutability can be restricted to pure
  function div(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).
,openzeppelin-solidity/contracts/math/SafeMath.sol:39:3: Warning: Function state mutability can be restricted to pure
  function sub(uint256 a, uint256 b) internal  returns (uint256) {
  ^ (Relevant source part starts here and spans across multiple lines).
,openzeppelin-solidity/contracts/math/SafeMath.sol:47:3: Warning: Function state mutability can be restricted to pure
  function add(uint256 a, uint256 b) internal  returns (uint256 c) {
  ^ (Relevant source part starts here and spans across multiple lines).

Error: Invalid number of arguments to Solidity function
    at Object.InvalidNumberOfSolidityArgs (/Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/web3/lib/
web3/errors.js:25:1)
    at SolidityFunction.validateArgs (/Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/web3/lib/web3/
function.js:74:1)
    at SolidityFunction.toPayload (/Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/web3/lib/web3/fun
ction.js:90:1)
    at SolidityFunction.sendTransaction (/Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/web3/lib/we
b3/function.js:163:1)
    at SolidityFunction.execute (/Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/web3/lib/web3/funct
ion.js:256:1)
    at /Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:204:1
    at new Promise (<anonymous>)
    at /Users/stephanegosselin/github/polymath-core/node_modules/truffle/build/webpack:/~/truffle-contract/contract.js:155:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
-------------------------------------------|----------|----------|----------|----------|----------------|
File                                       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------------------|----------|----------|----------|----------|----------------|
 contracts/                                |     23.2 |     7.32 |     27.5 |    23.85 |                |
  ModuleRegistry.sol                       |       50 |    21.43 |    33.33 |    46.15 |... 116,126,133 |
  Pausable.sol                             |     12.5 |     12.5 |       25 |       20 |... 35,42,43,44 |```

**Comment by cgewecke** [comment]
@thegostep 

I'm not positive but I don't think this happening during compilation - the error is coming from web3 and if it's happening immediately before the tests run it's likely the result of an undefined constructor parameter being passed to a deploy function in the migrations that Truffle runs before the tests. 

Not sure why SC would mess this up though . . . is it possible to disclose the Polymath branch you're working on?

**Comment by thegostep** [comment]
Thank you for the tips, I've looked through the migrations file again but there is nothing out of the ordinary. I am working on [poly_oracle](https://github.com/PolymathNetwork/polymath-core/tree/poly_oracle).

**Comment by thegostep** [comment]
Yes! That was it. Thank you for catching my slip up.

**Comment by cgewecke** [comment]
@thegostep Oh good, glad it works.
