### ISSUE TITLE
Error: Exceeds block gas limit when Norpc: true

### ISSUE THREAD

**Issue by asoong** [sc-forks/solidity-coverage#270]
Hi again,

I'm trying to have coverage run on a local testrpc (via `norpc: true`) instance because we're loading some contracts from a blockchain snapshot when we fire up ganache (0x contracts). Our script to run testrpc is:
`ganache-cli --db blockchain --networkId 50 --accounts 20 -l 10000000 -e 1000000 -m 'concert load couple harbor equip island argue ramp clarify fence smart topic'"`

I've updated both my `truffle.js` and my `.solcover.js` to point to port 8545. The test rpc picks it up but then fails immediately with a `Error: Exceeds block gas limit` message. Any thoughts on how i'm running my local chain differently than solidity-cover?

The branch in question can be found here:
https://github.com/SetProtocol/set-protocol-contracts/pull/145
Specs in: `zeroExExchangeWrapper.spec.ts` rely on the snapshot found in `/snapshots/0x` to be part of the chain. [CircleCI](https://circleci.com/gh/SetProtocol/set-protocol-contracts/1006?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by asoong** [comment]
I updated ganache to 6.1.2 and am using `./node_modules/.bin/testrpc-sc` to fire up testrpc, still running into the same rror:

> Error: Exceeds block gas limit
    at Object.InvalidResponse (/Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/Users/alexsoong/Source/set-protocol/set-protocol-contracts/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by asoong** [comment]
Whoops, I still included the gas limit as part of `testrpcOptions`, worked for me after removing and using the default of `0xfffffffffff`
