### ISSUE TITLE
Results incorrectly show 0% coverage

### ISSUE THREAD

**Issue by scoriiu** [sc-forks/solidity-coverage#299]
Hi,

Running the solidity-coverage results in 0% coverage, although clearly it's not true. In my example I run truffle test on a single file, which should result in >0% coverage results.

solidity-coverage v0.5.11
MacOS

.solcover:
```
module.exports = {
	copyPackages: ['openzeppelin-solidity'],
	compileCommand: 'node --max-old-space-size=4096 ../node_modules/truffle/build/cli.bundled.js compile --network coverage',
	testCommand: 'cp -a ../migrations ../coverageEnv && node --max-old-space-size=4096 ../node_modules/.bin/truffle test --network coverage ../tests/test-contract/test-contract.test.js',
	norpc: false,
	port: 8555,
	buildDirPath: '/build/contracts',
	skipFiles: ['Migrations.sol'],
};
```

truffle.js:
```
require('babel-register');
require('babel-polyfill');


module.exports = {
	networks: {
		coverage: {
			host: 'localhost',
			network_id: '*', // eslint-disable-line camelcase
			port: 8555,
			gas: 0xfffffffffff,
			gasPrice: 0x01,
		},
	},

	mocha: {
		reporter: 'eth-gas-reporter',
		reporterOptions : {
			currency: 'USD',
			gasPrice: 0x01
		}
	},

	solc: {
		optimizer: {
			enabled: true,
			runs: 200
		}
	},
};
```

Results:
```
...
 11 passing (8s)

-------------------------|----------|----------|----------|----------|----------------|
File                     |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------|----------|----------|----------|----------|----------------|
 contracts/              |        0 |        0 |        0 |        0 |                |
  ERC20TokenMock.sol     |      100 |      100 |        0 |        0 |    17,21,25,29 |
  TestContract.sol       |        0 |        0 |        0 |        0 |... 370,377,378 | <<<<< 
  MockInclude.sol        |      100 |      100 |        0 |      100 |                |
-------------------------|----------|----------|----------|----------|----------------|
All files                |        0 |        0 |        0 |        0 |                |
-------------------------|----------|----------|----------|----------|----------------|

Istanbul coverage reports generated
Cleaning up...
Shutting down testrpc-sc (pid 29446)
Done.
```

PS: The process even crashes at the end if I don't touch the `allFiredEvents` file in advance. The crash trace:
```
10 silly lifecycle test-contract@0.0.1~coverage: Args: [ '-c', 'solidity-coverage' ]
11 silly lifecycle  test-contract@0.0.1~coverage: Returned: code: 1  signal: null
12 info lifecycle test-contract@0.0.1~coverage: Failed to exec coverage script
13 verbose stack Error: test-contract@0.0.1 coverage: `solidity-coverage`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

I'm not sure if this is a bug or if I do something wrong. Looking forward for your feedback.
Thanks!

**Comment by f0xx0f** [comment]
Hello! I have a similar problem. I'm trying to make a test coverage for metacoin. 
This is my [package.json](https://github.com/f0xx0f/testcoverage_metacoin/blob/master/package.json) and [truffle-config.js](https://github.com/f0xx0f/testcoverage_metacoin/blob/master/truffle-config.js). I run the commands `./node_modules/.bin/ganache-cli --port 8555 --gasLimit 0xfffffffffff` and `./node_modules/.bin/solidity-coverage` and  the result is an empty test coverage:
```
Generating coverage environment
Running: node --max-old-space-size=4096 ../node_modules/.bin/truffle compile --network coverage
(this can take a few seconds)...
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Writing artifacts to ./build/contracts

Instrumenting  ./coverageEnv/contracts/ConvertLib.sol
Instrumenting  ./coverageEnv/contracts/MetaCoin.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Running: node --max-old-space-size=4096 ../node_modules/.bin/truffle compile --network coverage
(this can take a few seconds)...
Compiling ./contracts/ConvertLib.sol...
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Writing artifacts to ./build/contracts

Running: node --max-old-space-size=4096 ../node_modules/.bin/truffle test --network coverage
(this can take a few seconds)...
Using network 'coverage'.

Compiling ./test/TestMetacoin.sol...


  TestMetacoin
    ✓ testInitialBalanceUsingDeployedContract (89ms)
    ✓ testInitialBalanceWithNewMetaCoin (85ms)

  Contract: MetaCoin
    ✓ should put 10000 MetaCoin in the first account
    ✓ should call a function that depends on a linked library (54ms)
    ✓ should send coin correctly (128ms)


  5 passing (8s)

-----------------|----------|----------|----------|----------|----------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------|----------|----------|----------|----------|----------------|
 contracts/      |        0 |        0 |        0 |        0 |                |
  ConvertLib.sol |        0 |      100 |        0 |        0 |              6 |
  MetaCoin.sol   |        0 |        0 |        0 |        0 |... 23,24,28,32 |
-----------------|----------|----------|----------|----------|----------------|
All files        |        0 |        0 |        0 |        0 |                |
-----------------|----------|----------|----------|----------|----------------|

Istanbul coverage reports generated
Cleaning up...
Done. 
```
Maybe I'm doing something wrong. Please help me.

**Comment by f0xx0f** [comment]
my problem solved. needed to use test-rpс instead ganache-cli
```
./node_modules/.bin/testrpc-sc --gasLimit 0xfffffffffff --port 8555
```
