### ISSUE TITLE
Solidity-coverage Fails To Install

### ISSUE THREAD

**Issue by munawarb** [sc-forks/solidity-coverage#354]
I'm trying to install solidity-coverage but the installation fails.
Here is my error log:
```
munawar@iot:~/crowdsale$ npm install --save-dev solidity-coverage
[..................] / rollbackFailedOptional: verb npm-session bc88cea049ed072
[..................] / rollbackFailedOptional: verb npm-session bc88cea049ed072
[..................] / rollbackFailedOptional: verb npm-session bc88cea049ed072
[..................] / rollbackFailedOptional: verb npm-session bc88cea049ed072
[..................] \ fetchMetadata: sill resolveWithNewModule solidity-covera
[..................] \ fetchMetadata: sill resolveWithNewModule solidity-covera
[..................] - fetchMetadata: sill resolveWithNewModule solidity-covera
npm WARN deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm WARN deprecated   npm i nyc
npm WARN deprecated Visit https://istanbul.js.org/integrations for other alternatives.
[..................] | fetchMetadata: WARN deprecated istanbul@0.4.5: This modu
[..................] \ fetchMetadata: WARN deprecated istanbul@0.4.5: This modu
.. etc ...
                                                                ^
../src/node-boilerplate/scrypt_params_async.cc:25:64: warning: bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>) is deprecated (declared at /home/munawar/.node-gyp/12.3.1/include/node/v8.h:3358): Use maybe version [-Wdeprecated-declarations]
   obj->Set(Nan::New("p").ToLocalChecked(), Nan::New<Integer>(p));
                                                                ^
../src/node-boilerplate/scrypt_params_async.cc:32:25: warning: v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const is deprecated (declared at ../../nan/nan.h:1674) [-Wdeprecated-declarations]
   callback->Call(2, argv);
                         ^
scrypt.target.mk:127: recipe for target 'Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o' failed
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
make: Leaving directory '/home/munawar/crowdsale/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.4.0-154-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/munawar/crowdsale/node_modules/scrypt
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
[            ......] - install: info lifecycle scrypt@6.0.3~install: Failed to
npm WARN crowdsale@1.0.0 No description
npm WARN crowdsale@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/munawar/.npm/_logs/2019-07-22T14_34_08_666Z-debug.log
munawar@iot:~/crowdsale$ 
```

The `crowdsale` directory is a truffle project.

**Comment by cgewecke** [comment]
I think the problem is this:
```
node -v v12.3.1
```
scrypt isn't working w/ Node 12 and it's affecting a large number of ethereum projects at the moment - see [web3 2913](https://github.com/ethereum/web3.js/issues/2913). 

If you're using `nvm` to manage your node installation could you try running `nvm use 10` and see if that works?

**Comment by munawarb** [comment]
Hi @cgewecke. Thanks so much for the quick response. This solution fixed the problem. I rolled back to Node 10.16.0 with `n 10.16.0` and the test script installed successfully after that.
