### ISSUE TITLE
Assembly LHS tuple assignments break instrumentation

### ISSUE THREAD

**Issue by dong77** [sc-forks/solidity-coverage#425]
On this branch of my project - https://github.com/Loopring/protocols/tree/coverage

Run `npm run coverage` inside `packages/loopring_v3` yield the following error:

```terminal
> truffle run coverage


> Using Truffle library from local node_modules.

> server:            http://127.0.0.1:8555
> truffle:           v5.0.41
> ganache-core:      v2.7.0
> solidity-coverage: v0.7.0-beta.2

Network Info
============
> id:      *
> port:    8555
> network: soliditycoverage


Instrumenting for coverage...
=============================

> iface/IAddressWhitelist.sol
> iface/IBlockVerifier.sol
> iface/IDecompressor.sol
> iface/IDowntimeCostCalculator.sol
> iface/IExchange.sol
> iface/IExchangeProxy.sol
> iface/IExchangeV3.sol
> iface/IImplementationManager.sol
> iface/ILoopring.sol
> iface/ILoopringV3.sol
> iface/IProtocolFeeVault.sol
> iface/ITokenSeller.sol
> iface/IUniversalRegistry.sol
> iface/IUserStakingPool.sol
> impl/BlockVerifier.sol
> impl/DowntimeCostCalculator.sol
> impl/ExchangeProxy.sol
> impl/ExchangeV3.sol
> impl/ImplementationManager.sol
> impl/libexchange/ExchangeAccounts.sol
> impl/libexchange/ExchangeAdmins.sol
> impl/libexchange/ExchangeBalances.sol
> impl/libexchange/ExchangeBlocks.sol
> impl/libexchange/ExchangeConstants.sol
> impl/libexchange/ExchangeData.sol
> impl/libexchange/ExchangeDeposits.sol
> impl/libexchange/ExchangeGenesis.sol
> impl/libexchange/ExchangeMode.sol
> impl/libexchange/ExchangeTokens.sol
> impl/libexchange/ExchangeWithdrawals.sol
> impl/LoopringV3.sol
> impl/LzDecompressor.sol
> impl/ProtocolFeeVault.sol
> impl/proxies/AutoUpgradabilityProxy.sol
> impl/proxies/ManualUpgradabilityProxy.sol
> impl/SignatureBasedAddressWhitelist.sol
> impl/UniswapTokenSeller.sol
> impl/UniversalRegistry.sol
> impl/UserStakingPool.sol
> lib/AddressUtil.sol
> lib/Authorizable.sol
> lib/BurnableERC20.sol
> lib/BytesUtil.sol
> lib/Claimable.sol
> lib/ERC20.sol
> lib/ERC20SafeTransfer.sol
> lib/ERC20Token.sol
> lib/Killable.sol
> lib/MathUint.sol
> lib/Ownable.sol
> lib/Poseidon.sol
> solidity-coverage cleaning up, shutting down ganache server
ParserError: Could not instrument: lib/Poseidon.sol. (Please verify solc can compile this file without errors.) extraneous input ',' expecting {'from', '{', '}', '(', 'for', 'function', 'address', 'calldata', 'if', 'assembly', 'return', 'byte', 'let', '=:', 'switch', DecimalNumber, HexNumber, HexLiteral, 'break', 'continue', Identifier, StringLiteral} (107:14)
    at Object.parse (/Users/d/Projects/protocols/packages/loopring_v3/node_modules/solidity-parser-antlr/dist/index.js:79:11)
    at Instrumenter.instrument (/Users/d/Projects/protocols/packages/loopring_v3/node_modules/solidity-coverage/lib/instrumenter.js:63:30)
    at API.instrument (/Users/d/Projects/protocols/packages/loopring_v3/node_modules/solidity-coverage/lib/api.js:101:48)
    at plugin (/Users/d/Projects/protocols/packages/loopring_v3/node_modules/solidity-coverage/dist/truffle.plugin.js:70:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.0.41 (core: 5.0.41)
Node v12.11.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopring_v3@3.0.0 coverage: `truffle run coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopring_v3@3.0.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by dong77** [comment]
`npm run compile` compiles all contract successfully.

**Comment by cgewecke** [comment]
@dong77 Thanks for opening.

It looks like Poseidon.sol has assembly statements that our parser (solidity-parser-antlr) is not handling correctly. The underlying issue can be seen in its [assembly grammar rules](https://github.com/solidityj/solidity-antlr4/blob/88c2be659adc4b65adce7efc48657cacb5ed9675/Solidity.g4#L300-L313)

However, I was able to parse successfully by using explicit `let` syntax in the assignment statements for functions returning tuples. 

**Example**
```diff
- t0, t1, t2, t3, t4 := sbox_full(t0, t1, t2, t3, t4, q)
+ let (t0, t1, t2, t3, t4) := sbox_full(t0, t1, t2, t3, t4, q)
```

I am not an assembly expert - is this substitution viable for your case?

**Comment by dong77** [comment]
Thank you  @cgewecke. Your suggestion seems working :) 👍 But I ran into another issue:

```terminal

> solidity-coverage cleaning up, shutting down ganache server
Error: ENOENT: no such file or directory, stat '/path/to/my_proj/transpiled/test'
    at Object.statSync (fs.js:926:3)
    at Object.files (/path/to/my_proj/node_modules/node-dir/lib/paths.js:161:21)
    at Object.getTestFilePaths (/path/to/my_proj/node_modules/solidity-coverage/dist/plugin-assets/plugin.utils.js:215:20)
    at plugin (/path/to/my_proj/node_modules/solidity-coverage/dist/truffle.plugin.js:91:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Truffle v5.0.41 (core: 5.0.41)
Node v12.11.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! loopring_v3@3.0.0 coverage: `truffle run coverage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the loopring_v3@3.0.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/d/.npm/_logs/2019-10-18T03_21_07_399Z-debug.log
```

**Comment by cgewecke** [comment]
@dong77 Maybe in package.json, rewriting the coverage command so it's more like `test`...?
```
"coverage": "npm run transpile && node --max-old-space-size=4096 npx truffle run coverage"
```

Not sure. There are also workflow hooks you might want to look at [here](https://github.com/sc-forks/solidity-coverage/blob/beta/docs/advanced.md#workflow-hooks)

**Comment by dong77** [comment]
Thank you. @cgewecke
