### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by jo-es** [sc-forks/solidity-coverage#543]
I'm trying to add coverage via the buidler plugin on a fairly large project. When trying to execute `buidler coverage` it throws the following error after downloading the compiler. Using buidlers `--max-memory 4096` or `--max-old-space-size=4096` does not solve the issue. I believe this issue is specific to solidity-coverage as it does not occur with `buidler compile`.

```
RuntimeError: memory access out of bounds
    at wasm-function[833]:1152
    at wasm-function[147]:18
    at wasm-function[21880]:5
    at invoke_ii (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/.coverage_cache/compilers/soljson-v0.6.11+commit.5ef660b1.js:1:22611188)
    at wasm-function[19560]:100
    at ccall (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/.coverage_cache/compilers/soljson-v0.6.11+commit.5ef660b1.js:1:8145)
    at /Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/.coverage_cache/compilers/soljson-v0.6.11+commit.5ef660b1.js:1:8495
    at runWithCallbacks (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/solc/wrapper.js:151:24)
    at compileStandard (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/solc/wrapper.js:207:14)
    at Object.compileStandardWrapper [as compile] (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/solc/wrapper.js:214:14)
    at Compiler.compile (/Users/johannes/Documents/dev/actus-protocol/ap-monorepo/packages/protocol/node_modules/@nomiclabs/buidler/src/internal/solidity/compiler/index.ts:38:29)
```

Repository: https://github.com/atpar/ap-monorepo/tree/feature/AP-688-merge-packages/packages/protocol
solidity-coverage: `^0.7.4`
buidler: `1.4.3`

Related issue: https://github.com/trufflesuite/truffle/issues/3076

**Comment by cgewecke** [comment]
@jo-es 

Yes, it looks like a memory issue related to the size of the source bundle passed to `solcjs`. Solidity-coverage "instruments" the code (e.g. inserts a lot of lines) and your project has ~170 files. 

`0.7.11` includes some new options to [reduce the instrumentation footprint][1] to manage this problem... 

Was able to get ap-monorepo/protocol to compile by:
+ upgrading to solidity-coverage@0.7.11
+ setting the `measureStatementCoverage` option to `false` in `.solcover.js`

With this setting, you'll get line, branch, and function coverage. but there won't be a separate Istanbul measurement for statements e.g

```solidity
// one line, two statements
uint x = 5; uint y = 7;
```

I *still* got a conventional heap allocation error while compiling (idk, I'm on a Mac maybe this is OS specific)
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

Just lmk if this doesn't work or is problematic for other reasons.
... but fixed this by re-writing your coverage command as:
```
node --max-old-space-size=4096 ./node_modules/.bin/buidler coverage
```
 

[1]: https://github.com/sc-forks/solidity-coverage/blob/master/docs/advanced.md#reducing-the-instrumentation-footprint

**Comment by jo-es** [comment]
Thanks @cgewecke updating to 0.7.11 fixed the issue!

**Comment by cgewecke** [comment]
@jo-es Ok cool, I'll document this in the running out of memory README section ...

Thanks for reporting!

**Comment by aakash4dev** [comment]
Solidity Smart contract has a size limit of 24.576 kb. If the smart contract size exceeds this limit, the Solidity compiler will give an error: "Memory access out of bounds".
read more: https://ethereum.org/en/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit
