### ISSUE TITLE
Solidity 0.7.0 Syntax breaks solidity-coverage

### ISSUE THREAD

**Issue by mudgen** [sc-forks/solidity-coverage#545]
When I run `npx buidler coverage --network coverage` I get this error:

```
ParserError: Could not instrument: GHSTStakingDiamond.sol. (Please verify solc can compile this file without errors.) extraneous input '.' expecting {'from', '{', '}', '(', 'for', 'function', 'address', 'calldata', 'if', 'assembly', 'return', 'byte', 'let', '=:', 'switch', 'callback', DecimalNumber, HexNumber, HexLiteral, 'break', 'continue', 'leave', 'payable', 'receive', Identifier, StringLiteralFragment} (75:14)
    at Object.parse (C:\Users\mudge\projects\aavegotchi\ghst-staking\node_modules\solidity-coverage\node_modules\@solidity-parser\parser\dist\index.js:79:11)
    at Instrumenter.instrument (C:\Users\mudge\projects\aavegotchi\ghst-staking\node_modules\solidity-coverage\lib\instrumenter.js:67:30)
    at API.instrument (C:\Users\mudge\projects\aavegotchi\ghst-staking\node_modules\solidity-coverage\lib\api.js:91:48)
    at SimpleTaskDefinition.action (C:\Users\mudge\projects\aavegotchi\ghst-staking\node_modules\solidity-coverage\plugins\buidler.plugin.js:93:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Environment._runTaskDefinition (C:\Users\mudge\projects\aavegotchi\ghst-staking\node_modules\@nomiclabs\buidler\src\internal\core\runtime-environment.ts:203:14)
    at main (C:\Users\mudge\projects\aavegotchi\ghst-staking\node_modules\@nomiclabs\buidler\src\internal\cli\cli.ts:157:5) {
  errors: [
    {
      message: "extraneous input '.' expecting {'from', '{', '}', '(', 'for', 'function', 'address', 'calldata', 'if', 'assembly', 'return', 'byte', 'let', '=:', 'switch', 'callback', DecimalNumber, HexNumber, HexLiteral, 'break', 'continue', 'leave', 'payable', 'receive', Identifier, StringLiteralFragment}",
      line: 75,
      column: 14
    }
  ]
}
```

The code that it complains about is this:
```Solidity
assembly {
    ds.slot := position
}
```
The dot in `ds.slot` is new Solidity 0.7.0 syntax that breaks the coverage tool.

Info about the dot syntax is here: https://solidity.readthedocs.io/en/v0.7.4/070-breaking-changes.html#inline-assembly

**Comment by cgewecke** [comment]
@mudgen 

Oh thanks for reporting. Looks like we just need to update [solidity-parser/parser to 0.8.0][1] here...

[1]: https://github.com/solidity-parser/parser/releases/tag/v0.8.0

**Comment by cgewecke** [comment]
Sorry for the delay fixing this. `0.7.12` contains the latest solidity-parser.
