### ISSUE TITLE
circular dependency warning in sc-istanbul

### ISSUE THREAD

**Issue by clifton** [sc-forks/solidity-coverage#607]
when importing the latest `solidity-coverage` into my hardhat project, i get a circular dependency warning on `VERSION` from https://github.com/gotwarlost/istanbul/blob/bc84c315271a5dd4d39bcefc5925cfb61a3d174a/lib/command/help.js#L9 which hasn't been updated since 2014.

```
> (node:3211) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:823:11)
    at Object.get (internal/modules/cjs/loader.js:837:5)
    at Object.<anonymous> (node_modules/sc-istanbul/lib/command/help.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at node_modules/sc-istanbul/lib/util/factory.js:56:35
```

**Comment by cgewecke** [comment]
Thanks for reporting...

Triage notes: 
+ These warnings begin w/ Node 14
+ Culprit appears to be in [istanbul/lib/command/help][1] (can safely disable...)

Upgrading to use the nyc api is being tracked in issue #455. 

[1]: https://github.com/sc-forks/istanbul/blob/b5628dbcb9242542e9bbf1fb82a14dbc8d063884/lib/command/help.js#L9

**Comment by dtp5** [comment]
All `npx hardhat` commands pollute the terminal with this warning just by importing `solidity-coverage` into `hardhat.config.ts`, which gets especially irritating in yarn/npm scripts with multiple non-`hh coverage` commands.

**Comment by cgewecke** [comment]
@clifton @dtp5 Apologies, this is fixed in the latest version of sc-istanbul (`0.4.6`) 

If you uninstall / re-install solidity-coverage, the warning should be gone. Please just lmk if you're still seeing or running into issues.

**Comment by paulrberg** [comment]
Just bumped into this issue. Unfortunately, installing solidity-coverage@0.7.16 doesn't clear the warning, it looks like sc-istanbul@0.4.5 is still used. I also tried solidity-coverage@0.8.0-beta.0 but it didn't work.

Running `yarn why sc-istanbul` with solidity-coverage@0.7.16 yields this output:

```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "sc-istanbul"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sc-istanbul@0.4.5"
info Reasons this module exists
   - "solidity-coverage" depends on it
   - Hoisted from "solidity-coverage#sc-istanbul"
info Disk size without dependencies: "1.24MB"
info Disk size with unique dependencies: "8.25MB"
info Disk size with transitive dependencies: "15.73MB"
info Number of shared dependencies: 34
✨  Done in 0.76s
```

And running `yarn why sc-istanbul` with solidity-coverage@0.8.0-beta.0 yields this output:

```
yarn why v1.22.10
[1/4] 🤔  Why do we have the module "sc-istanbul"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "sc-istanbul@0.4.5"
info Reasons this module exists
   - "solidity-coverage" depends on it
   - Hoisted from "solidity-coverage#sc-istanbul"
info Disk size without dependencies: "1.24MB"
info Disk size with unique dependencies: "8.22MB"
info Disk size with transitive dependencies: "15.7MB"
info Number of shared dependencies: 34
✨  Done in 0.80s.
```

I used my [solidity-template](https://github.com/paulrberg/solidity-template) for this, commit [8244999](https://github.com/paulrberg/solidity-template/commit/8244999d30b27497b3f867102d5679216e4ba582).

**Comment by cgewecke** [comment]
@paulrberg Did you uninstall and re-install? 

I will explicitly update this dep in the next release (0.7.17) but you should get  `sc-instanbul@0.4.6` on a completely fresh install since [it's floating on a caret][1]. 

[1]: https://github.com/sc-forks/solidity-coverage/blob/3c0f3a5c7db26e82974873bbf61cf462072a7c6d/package.json#L42

**Comment by paulrberg** [comment]
Whops, I didn't uninstall, I just forcefully upgraded to solidity-coverage@0.7.16. Now the warning went away.

Thanks!
