### ISSUE TITLE
ls no such file or directory: ./coverageEnv/build/contracts/*.json and Error: ENOENT: no such file or directory, open './allFiredEvents'

### ISSUE THREAD

**Issue by eerkaijun** [sc-forks/solidity-coverage#612]
Hi, when I am running `npx solidity-coverage`, there are some errors as shown. Any ideas what might be the possible reasons? 

```
Instrumenting  ./coverageEnv/contracts/Marketplace.sol
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/TicketsFactory.sol
Running: truffle compile --network coverage 
(this can take a few seconds)...

Compiling your contracts...
===========================
Error: Could not find library from any sources; imported from @openzeppelin/contracts/access/Ownable.sol
    at Resolver.<anonymous> (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:54:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:5:42)
Truffle v5.1.45 (core: 5.1.45)
Node v12.18.3
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Launched testrpc on port 8555
Running: truffle test --network coverage 
(this can take a few seconds)...

Compiling your contracts...
===========================
Error: Could not find library from any sources; imported from @openzeppelin/contracts/access/Ownable.sol
    at Resolver.<anonymous> (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:54:1)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/resolver/dist/lib/resolver.js:5:42)
Truffle v5.1.45 (core: 5.1.45)
Node v12.18.3
Cleaning up...
Shutting down testrpc-sc (pid 46143)
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

PS: To maybe help with easier debugging, my .solcover.js file as below: 
```
module.exports = {
    copyPackages: ['@openzeppelin/contracts']
};
```

**Comment by cgewecke** [comment]
@eerkaijun It looks like you're using a very old version of solidity-coverage. 

Please upgrade both Truffle and solidity-coverage to their latest versions and follow the README instructions for adding solidity-coverage to your truffle config as a plugin.

The 0.6.x version is no longer supported.
