### ISSUE TITLE
Unable to require Truffle library locally or globally

### ISSUE THREAD

**Issue by eerkaijun** [sc-forks/solidity-coverage#613]
```
 Unable to require Truffle library locally or globally.
⚠️  Using fallback Truffle library module instead (v5.0.31)
⚠️  Truffle V5 must be a local dependency for fallback to work.

Error: Unable to load plugin copy of Truffle library module. Try installing Truffle >= v5.0.31 locally or globally.
Caught error message: Error: Cannot find module 'original-require'
Require stack:
- /home/kaijun/Documents/blockchain-ticketing/node_modules/solidity-coverage/plugins/resources/truffle.library.js
- /home/kaijun/Documents/blockchain-ticketing/node_modules/solidity-coverage/plugins/resources/truffle.utils.js
- /home/kaijun/Documents/blockchain-ticketing/node_modules/solidity-coverage/plugins/truffle.plugin.js
- /home/kaijun/.npm-global/lib/node_modules/truffle/node_modules/original-require/index.js
- /home/kaijun/.npm-global/lib/node_modules/truffle/build/cli.bundled.js

    at Object.loadLibrary (/home/kaijun/Documents/blockchain-ticketing/node_modules/solidity-coverage/plugins/resources/truffle.utils.js:180:11)
    at plugin (/home/kaijun/Documents/blockchain-ticketing/node_modules/solidity-coverage/plugins/truffle.plugin.js:30:28)
    at Object.run (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/run/run.js:59:1)
    at Object.run (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/run/index.js:30:1)
    at Command.run (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
    at Object.<anonymous> (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/packages/core/cli.js:56:1)
    at __webpack_require__ (/home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:19:1)
    at /home/kaijun/.npm-global/lib/node_modules/truffle/build/webpack:/webpack/bootstrap:83:1
    at Object.<anonymous> (/home/kaijun/.npm-global/lib/node_modules/truffle/build/cli.bundled.js:89:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Truffle v5.1.45 (core: 5.1.45)
Node v12.18.3
```
I've already have Truffle installed globally so I am unsure why this happens? 

Using solidity coverage version 0.7.14.

**Comment by eerkaijun** [comment]
Okay, I managed to solve this, we need to have truffle as a local dependency.
