### ISSUE TITLE
Hardhat forking w/ remote accounts: "Cannot read property 'match' of undefined"

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#622]
Cross-posting report from HH discord thread

**Error**
```
TypeError: Cannot read property 'match' of undefined
    at derivePrivateKeys (/Users/me/Desktop/contracts/node_modules/hardhat/src/internal/core/providers/util.ts:18:14)
```    
**Stack trace**
```
(node:92771) Warning: Accessing non-existent property 'VERSION' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
    at Object.get (internal/modules/cjs/loader.js:664:5)
    at Object.<anonymous> (/Users/me/Desktop/contracts/node_modules/sc-istanbul/lib/command/help.js:9:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/me/Desktop/contracts/node_modules/sc-istanbul/lib/util/factory.js:56:35
 ```` 

**Config**
```
// pending
```

**Comment by JimLynchCodes** [comment]
why no one gives a f about this error?

**Comment by cgewecke** [comment]
@JimLynchCodes This error only occurs if you are running the HH client as an independent node. Please try running the tool using the hardhat network (with forking configuration).
