### ISSUE TITLE
[Truffle] Tests timeout / client disconnects on long running test suites

### ISSUE THREAD

**Issue by ecp4224** [sc-forks/solidity-coverage#665]
I'm running into an odd issue running coverage on my tests. All my tests pass when I run them normally, when I run coverage it runs 489 tests before throwing a timeout error

I'm aware of the FAQ and how to disable timeout errors, however even after setting the following in my `.solcover.js` file, it will still throw a timeout error

```
  mocha: {
    enableTimeouts: false,
    before_timeout: 0
  }
```

What's even more strange is that it also throws a provider error afterwards before stopping all together. The full error output is below

```
            1) sets the token extension (failed)
            2) "after each" hook: after test for "sets the token extension" (failed)

  Contract: ERC1400 with sender and recipient hooks
    3) "before all" hook: prepare suite in "Contract: ERC1400 with sender and recipient hooks" (failed)


  489 passing (59m)
  3 failing

  1) Contract: ERC1400HoldableCertificate with token extension
       setTokenExtension
         when the caller is the contract owner
           when the the validator contract is not already a minter
             when there is was no previous validator contract
               sets the token extension:
     Error: Timeout of 300000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/UniversalToken/UniversalToken/test/TokenExtension.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) Contract: ERC1400HoldableCertificate with token extension
       "after each" hook: after test for "sets the token extension":
     ProviderError: 
Could not connect to your Ethereum client with the following parameters:
    - host       > 127.0.0.1
    - port       > 8555
    - network_id > *
Please check that your Ethereum client:
    - is running
    - is accepting RPC connections (i.e., "--rpc" or "--http" option is used in geth)
    - is accessible over the network
    - is properly configured in your Truffle configuration file (truffle-config.js)

      at /home/runner/work/UniversalToken/UniversalToken/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:73:1
      at /home/runner/work/UniversalToken/UniversalToken/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:102:1
      at XMLHttpRequest.request.onreadystatechange (node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
      at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpRequestError (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
      at ClientRequest.<anonymous> (node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
      at Socket.socketOnEnd (_http_client.js:458:9)
      at endReadableNT (_stream_readable.js:1241:12)
      at processTicksAndRejections (internal/process/task_queues.js:84:21)

  3) Contract: ERC1400 with sender and recipient hooks
       "before all" hook: prepare suite in "Contract: ERC1400 with sender and recipient hooks":
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/runner/work/UniversalToken/UniversalToken/test/UserExtension.test.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)
```

This is also inconsistent, sometimes coverage will run all the way through, sometimes it'll timeout at a different test. However the error output is always mostly the same when it does error

My guess is that the internal ganache server is crashing, but there's no way for me to verify this..

How to reproduce:

```
git clone https://github.com/ConsenSys/UniversalToken
cd UniversalToken
yarn
yarn coverage
```

**Comment by cgewecke** [comment]
This might be due to [an issue Truffle has with Web3][1] (esp on long running test suites)

Could you see if this resolves when setting the key below in your coverage network to true
```
disableConfirmationListener: true
```

and running the coverage command as `truffle run coverage --network coverage` ? 

[1]: https://github.com/trufflesuite/truffle/pull/3566

**Comment by ecp4224** [comment]
> Could you see if this resolves when setting the key below in your coverage network to true

I will try this and report back

I also tried adding `configureYulOptimizer: true` since the contracts are also quite big and thought maybe that had something to do with it

> and running the coverage command as truffle run coverage --network coverage ?

I believe we already do this in the `.solcover.js` file 
```
module.exports = {
  configureYulOptimizer: true,
  testCommand:
    "node --max-old-space-size=4096 ../node_modules/.bin/truffle test test/TokenExtension.test.js --network coverage",
  compileCommand:
    "node --max-old-space-size=4096 ../node_modules/.bin/truffle compile --network coverage",
  skipFiles: ["tokens/ERC20Token", "tokens/ERC721Token", "tools/FundIssuer"],
  copyPackages: ["@openzeppelin/contracts"],
  mocha: {
    enableTimeouts: false,
    before_timeout: 0
  }
};

```

**Comment by cgewecke** [comment]
Ah some of the options in your .solcover.js are no longer supported. They're for the v0.6.x version. Those have migrated to command line options passed when invoking the plugin via truffle (or hardhat) command.

**Comment by hellwolf** [comment]
I had the same issue.

Setting to:

```
        coverage: {
            host: "localhost",
            port: 8555, // <-- If you change this, also set the port option in .solcover.js.

            // ditto
            disableConfirmationListener: true,
        },
```

And making sure network is selected works:

```
$ truffle run coverage --network coverage --file testsuites/all-contracts.js
```

**Comment by ecp4224** [comment]
Adding `disableConfirmationListener: true` to my `coverage` network and adding `--network coverage` to the command-line scripts resolved this issue for me.

Should this be documented under FAQ? I think it's safe to close this issue

**Comment by cgewecke** [comment]
> Should this be documented under FAQ?

Yes maybe, although honestly I think it's a problem that should be fixed at Truffle. It affects any long running test suite ... people just tend to run into it with coverage first because it's slower.  

I re-wrote the issue description a bit. Will leave this open for now so people can find it easily.

**Comment by cgewecke** [comment]
Truffle related, closing.
