### ISSUE TITLE
testrpc-sc crashing with db error

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#70]
Two cases:
From [zeppelin CI build 433](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/builds/253602206) at the start of the Claimable test. i.e. testrpc-sc launches ok, runs for a while and crashes.
```
/home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/ethereumjs-testrpc-sc/node_modules/web3-provider-engine/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,bi
NotFoundError: Key not found in database
    at /home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/level-sublevel/shell.js:101:18
    at /home/travis/build/OpenZeppelin/zeppelin-solidity/node_modules/level-sublevel/nut.js:121:19
```

From [Gnosis build 100.1](https://travis-ci.org/gnosis/gnosis-contracts/jobs/253611700) at the start of the run, before truffle compile.
```
/home/travis/build/gnosis/gnosis-contracts/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"
Error: Cannot find module 'levelup/lib/errors'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/gnosis/gnosis-contracts/node_modules/level-sublevel/shell.js:4:14)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by cgewecke** [comment]
Interestingly . . . Zeppelin had a [subsequent build](https://travis-ci.org/OpenZeppelin/zeppelin-solidity/builds/253657482) from a different PR where everything ran ok.

**Comment by cgewecke** [comment]
I suspect the zeppelin crash is actually related to the tests that precede the Claimable tests. They advance the block. . . .

**Comment by cgewecke** [comment]
I'm going to close because both Zeppelin and Gnosis have had several successful CI builds since this was opened and we're on a new testrpc anyway. Will re-open if this starts happening again and it's not an upstream problem.
