### ISSUE TITLE
Error: Cannot find module 'solidity-coverage'

### ISSUE THREAD

**Issue by JimLynchCodes** [sc-forks/solidity-coverage#746]
I run the script `yarn add solidity-coverage --dev` and add the require statement in to my hardhat.config.js

However, it still can't be found...

```
hardhat (master) 🏖  yarn cov
yarn run v1.22.19
$ hardhat coverage
An unexpected error occurred:

Error: Cannot find module 'solidity-coverage'
Require stack:
- /Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/hardhat.config.js
- /Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/hardhat.config.js:17:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/hardhat.config.js',
    '/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/cli/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
hardhat (master) 🏖  yarn cov
yarn run v1.22.19
$ hardhat coverage
An unexpected error occurred:

Error: Cannot find module 'solidity-coverage'
Require stack:
- /Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/hardhat.config.js
- /Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/cli/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/hardhat.config.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/hardhat.config.js',
    '/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/jim/Git-Projects/AppleTreeNFT-Smart-Contracts/packages/hardhat/node_modules/hardhat/internal/cli/cli.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cgewecke** [comment]
It seems like you got this to install and hit a different error with running tests on an independent forked client? #746?

**Comment by JimLynchCodes** [comment]
@celeduc why are you linking back to this issue?

And what are you talking about "forked client"?
