### ISSUE TITLE
Error in plugin solidity-coverage: TypeError: Cannot read properties of undefined (reading 'events')

### ISSUE THREAD

**Issue by OxSnosh** [sc-forks/solidity-coverage#807]
Does anyone know why i am getting this error. I have a node running on localhost. However i cannot get solidity coverage to run my test files.

**Comment by OxSnosh** [comment]
Error in plugin solidity-coverage: TypeError: Cannot read properties of undefined (reading 'events')

HardhatPluginError: TypeError: Cannot read properties of undefined (reading 'events')
    at SimpleTaskDefinition.action (/Users/oxsnosh/Documents/files/MetaNations/node_modules/solidity-coverage/plugins/hardhat.plugin.js:274:35)
    at async Environment._runTaskDefinition (/Users/oxsnosh/Documents/files/MetaNations/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at async Environment.run (/Users/oxsnosh/Documents/files/MetaNations/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at async main (/Users/oxsnosh/Documents/files/MetaNations/node_modules/hardhat/src/internal/cli/cli.ts:218:5)
error Command failed with exit code 1.

**Comment by cgewecke** [comment]
> I have a node running on localhost

Coverage doesn't work with localhost. It needs to launch the client itself after hooking into its internals to track the execution trace.
