### ISSUE TITLE
Error: truffle-plugin.json not found in the solidity-coverage plugin package!

### ISSUE THREAD

**Issue by onchezz** [sc-forks/solidity-coverage#808]
can anyone help me navigate this problem while running solidity coverage 
error:
truffle run coverage 
  shell: /usr/bin/bash -e {0}
  

Error: truffle-plugin.json not found in the solidity-coverage plugin package!

Truffle v[5](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5643193005/job/15284529941#step:6:5).11.0 (core: 5.11.0)
Node v1[6](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5643193005/job/15284529941#step:6:7).20.1

**Comment by clauBv23** [comment]
It might be related to truffle not being supported on this repo, see [Release 0.8.0](https://github.com/sc-forks/solidity-coverage/releases/tag/v0.8.0)

> Note to Truffle users
solidity-coverage for Truffle is moving to its own repository and published under a different name (details soon...).

**Comment by onchezz** [comment]
version 0.7 is bring up this error i already tried

truffle run coverage 
  shell: /usr/bin/bash -e {0}
  
Error: Cannot find module '/opt/hostedtoolcache/node/1[4](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:4).21.3/x64/lib/node_modules/solidity-coverage/plugins/truffle.plugin.js'
Require stack:
- /opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/truffle/node_modules/original-require/index.js
- /opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:1[5](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:5))
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Plugin.loadModule (/opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/truffle/build/webpack:/packages/plugins/dist/lib/Plugin.js:[5](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:6)2:1)
    at Plugin.loadCommand (/opt/hostedtoolcache/node/14.21.3/x[6](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:7)4/lib/node_modules/truffle/build/webpack:/packages/plugins/dist/lib/Plugin.js:29:1)
    at Object.run (/opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/run/runHandler.js:18:1)
    at internal/util.js:341:30
    at new Promise (<anonymous>)
    at bound run (internal/util.js:340:12)
    at Object.module.exports [as run] (/opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/truffle/build/webpack:/packages/core/lib/commands/run/run.js:18:1)
    at runCommand (/opt/hostedtoolcache/node/14.21.3/x64/lib/node_modules/truffle/build/webpack:/packages/core/lib/command-utils.js:29[7](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:8):1)
Truffle v5.[11](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:12).0 (core: 5.11.0)
Node v[14](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:15).[21](https://github.com/TwigaDEVs/kazikrypto/actions/runs/5646371044/job/15294124153#step:7:22).3
Error: Process completed with exit

**Comment by cgewecke** [comment]
Truffle support deprecated, sorry.
