### ISSUE TITLE
named mapping keys printing large logs

### ISSUE THREAD

**Issue by hexpaydaydev** [sc-forks/solidity-coverage#815]
regarding: #799 

after updating the package, the errors appear to be printing
```
Error found while parsing the following file: ./contracts/AuthorizationManager.sol

ParserError: extraneous input 'key' expecting '=>' (18:18)
    at Object.parse (~/hexpayday/stake-manager/node_modules/@solidity-parser/parser/dist/index.cjs.js:36973:11)
    at ~/hexpayday/stake-manager/node_modules/surya/lib/mdreport.js:60:23
    at _loop (~/hexpayday/stake-manager/node_modules/surya/lib/mdreport.js:69:6)
    at Object.mdreport (~/hexpayday/stake-manager/node_modules/surya/lib/mdreport.js:185:18)
    at SolidityMetricsContainer.generateReportMarkdown (~/hexpayday/stake-manager/node_modules/solidity-code-metrics/src/metrics/metrics.js:204:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      message: "extraneous input 'key' expecting '=>'",
      line: 18,
      column: 18
    }
  ]
}
```
the process does not exit, which is great! but it would be great to not have these logs if possible

example repo can be found here: https://github.com/hexpay-day/stake-manager

**Comment by hexpaydaydev** [comment]
happens with named values as well: ```
  errors: [
    {
      message: "extraneous input 'key' expecting '=>'",
      line: 18,
      column: 18
    },
    {
      message: "extraneous input 'settings' expecting ')'",
      line: 18,
      column: 33
    }
  ]
```

**Comment by cgewecke** [comment]
Hi @hexpaydaydev, I've added this syntax to the integration tests here in #816 - they seem to be passing without any weird additional output. 

The stack trace you posted above suggests the problem is coming from the Consensys Surya tool. Are you running coverage and other analytics back to back? 

```
at Object.mdreport (~/hexpayday/stake-manager/node_modules/surya/lib/mdreport.js:185:18)
```

**Comment by hexpaydaydev** [comment]
ah, you're right. wrong repo
