### ISSUE TITLE
Error: Bytecode is not a valid hex string using OZ upgrades deployProxy

### ISSUE THREAD

**Issue by karacurt** [sc-forks/solidity-coverage#872]
I am facing the following error: 

`Error: Bytecode is not a valid hex string`

The error happens when we run `npx hardhat compile` and then runs `npx hardhat coverage`

The line in the code is trying to call `upgrades.deployProxy` to deploy an upgradeable contract

Hardhat version:  `"hardhat": "^2.12.6"`
Solidity Coverage version:  `"solidity-coverage": "^0.8.2",`

**Comment by cgewecke** [comment]
@karacurt Could you try upgrading to the latest version of solidity-coverage (0.8.10) and also make sure your hardhat version is newer, e.g 2.20.0 or higher?

If the problem persists could you provide the full stack trace of the error?

**Comment by karacurt** [comment]
Just upgraded both packages and the error keeps happening. Here is the stack error:

`     Error: Bytecode is not a valid hex string
      at hashBytecode (node_modules/@openzeppelin/upgrades-core/src/version.ts:31:11)
      at hashBytecodeWithoutMetadata (node_modules/@openzeppelin/upgrades-core/src/version.ts:47:10)
      at getVersion (node_modules/@openzeppelin/upgrades-core/src/version.ts:14:24)
      at getUnlinkedBytecode (node_modules/@openzeppelin/upgrades-core/src/validate/query.ts:130:33)
      at getDeployData (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:48:47)
      at async deployProxyImpl (node_modules/@openzeppelin/hardhat-upgrades/src/utils/deploy-impl.ts:72:22)
      at async Proxy.deployProxy (node_modules/@openzeppelin/hardhat-upgrades/src/deploy-proxy.ts:35:28)
      at async deploySftMarketplaceContracts (test/fixtures/OriumSftMarketplaceFixture.ts:17:32)
      at async loadFixture (node_modules/@nomicfoundation/hardhat-network-helpers/src/loadFixture.ts:59:18)
      at async Context.<anonymous> (test/OriumSftMarketplace.test.ts:43:101)
`

**Comment by cgewecke** [comment]
Am going close because in #870 the project is using `deployProxy` without problems and they're on the latest version.  Issue is likely that deps are a couple years out of date in your project but if you continue to see this after bumping everything please ping and I'll re-open.
