### ISSUE TITLE
Fix zeppelin in CI

### ISSUE THREAD

**Issue by cgewecke** [sc-forks/solidity-coverage#878]
Recent changes at zeppelin have resulted in two GovernorTimelock tests failing for weird time-related reasons.

They fail on the current master branch and at v0.8.5 (the version they're using successfully in github actions). Notably, Circle is taking about 50% longer to execute their suite than github is - there may be some async issue in those tests.

Temporarily exiting the E2E test with `0` so we can still use their suite as a sanity check.
```
1) GovernorTimelockAccess
       using $ERC20VotesTimestampMock
         "before each" hook for "cancels restricted with delay after queue (internal)":
     Uncaught Error: HardhatChaiMatchersAssertionError: Assertion error: receipt should not be null
      at process.<anonymous> (hardhat/async-test-sanity.js:2:9)
      at process.emit (node:events:526:35)
      at process.emit (node_modules/source-map-support/source-map-support.js:516:21)
      at emit (node:internal/process/promises:150:20)
      at processPromiseRejections (node:internal/process/promises:284:27)
      at processTicksAndRejections (node:internal/process/task_queues:96:32)

  2) GovernorTimelockAccess
       using $ERC20VotesTimestampMock
         "before each" hook for "cancels restricted with delay after queue (internal)":
     Error: done() called multiple times in hook <GovernorTimelockAccess using $ERC20VotesTimestampMock "before each" hook for "cancels restricted with delay after queue (internal)"> of file /home/circleci/project/openzeppelin-contracts/test/governance/extensions/GovernorTimelockAccess.test.js
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by cgewecke** [comment]
This is fine now.
